# coding: utf-8

"""
    HLS - DAC (Data Acquisition and Control)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2017-01-23T14:55:49Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import hls_dac
from hls_dac.rest import ApiException
from hls_dac.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = hls_dac.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_data_get(self):
        """
        Test case for data_get

        
        """
        pass

    def test_data_put(self):
        """
        Test case for data_put

        
        """
        pass

    def test_device_delete(self):
        """
        Test case for device_delete

        
        """
        pass

    def test_device_get(self):
        """
        Test case for device_get

        
        """
        pass

    def test_device_post(self):
        """
        Test case for device_post

        
        """
        pass

    def test_device_put(self):
        """
        Test case for device_put

        
        """
        pass

    def test_devices_get(self):
        """
        Test case for devices_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
