# coding: utf-8

"""
    HLS - DAC (Data Acquisition and Control)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2017-01-23T14:55:49Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import hls_dac
from hls_dac.rest import ApiException
from hls_dac.models.data import Data


class TestData(unittest.TestCase):
    """ Data unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData(self):
        """
        Test Data
        """
        model = hls_dac.models.data.Data()


if __name__ == '__main__':
    unittest.main()
